java_library(
    name = "common",
    srcs = [
        "CheckReturnValue.java",
        "Nullable.java",
        "WillCloseWhenClosed.java",
        "WillNotClose.java"
    ],
    visibility = ["//visibility:public"],
)
